apiVersion: v1
kind: Service
metadata:
  name: ts
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: typesense
  ports:
    - name: http
      port: 8108
      targetPort: 8108
