apiVersion: v1
kind: Service
metadata:
  name: typesense-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: typesense
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8108
