apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  namespace: {{ .Values.namespace }}
spec:
  serviceName: ts
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: typesense
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/opt/typesense-server"
            - "-d"
            - "/usr/share/typesense/data"
            - "-a"
            - "$(API_KEY)"
            - "--api-port"
            - "8108"
            - "--peering-port"
            - "8107"
            - "--nodes"
            - "/usr/share/typesense/nodes"
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-secret
                  key: api-key
          ports:
            - containerPort: 8108
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nodeslist
              mountPath: /usr/share/typesense
            - name: data
              mountPath: /usr/share/typesense/data
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: nodeslist
          configMap:
            name: nodeslist
            items:
              - key: nodes
                path: nodes
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
